"""2nd migration

Revision ID: ec43cdb5b9ae
Revises: 5e6c5da96176
Create Date: 2023-08-24 21:40:58.281465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec43cdb5b9ae'
down_revision = '5e6c5da96176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetroomorm', sa.Column('all_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetroomorm', 'all_description')
    # ### end Alembic commands ###
