"""add all_description

Revision ID: 02
Revises: 01
Create Date: 2023-08-17 17:24:12.456082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02'
down_revision = '01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetroom', sa.Column('all_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetroom', 'all_description')
    # ### end Alembic commands ###
